[xray-ip-limit]
enabled = true
backend = auto
filter = xray-ip-limit
logpath = /var/log/xray-manager/ip-limit.log
maxretry = 2
findtime = 60
bantime = 600
action = iptables-allports[name=xray-ip-limit]
